language: csharp
solution: Commander.sln

install:
  - nuget restore Commander.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release Commander.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Commander.Tests/bin/Release/Commander.Tests.dll