language: csharp
solution: Commander.sln

script:
  - msbuild /p:Configuration=Release Commander.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./Commander.Tests/bin/Release/Commander.Tests.dll